Repository sas-fossdev/saspes, pull requests merged in 2019-10, with the labels that each got.

#19 migrating the website fromgschool.ydgkim.com/saspowerschool to github
  README.md
  src/js/components/ExtensionInfo.vue
  src/manifest - chromium.json
  src/manifest.json
  src/ui/options.html
Labels: maintenance

#20 Bugfix: Final Percent and Shown Grade Strange
  src/js/components/HypoAssignment.vue
Labels: bug

#26 Add No Warranty Disclaimer
  README.md
  src/js/components/ExtensionInfo.vue
Labels: enhancement

#16 Migrate HypoGrades to Vue
  package-lock.json
  package.json
  src/.eslintrc.json
  src/css/spse.css
  src/js/components/HypoAssignment.vue
  src/js/components/HypoGrades.vue
  src/js/helpers.js
  src/js/saspowerschoolff.js
Labels: maintenance

#40 Remove Drone OSS CI
  .drone.yml
  README.md
  package-lock.json
  package.json
Labels: discussion, maintenance

#41 Fix Incorrect GPA Conversion When Grade is F
  src/js/__tests__/parsers.js
  src/js/helpers.js
Labels: bug
