Repository sas-fossdev/saspes, pull requests merged in 2020-02, with the labels that each got.

#100 Add configuration for github_changelog_generator
  .github_changelog_generator
  CONTRIBUTING.md
Labels: enhancement

#101 Open Beta v0.18.1 Release
  CHANGELOG.md
  package-lock.json
  package.json
Labels: maintenance

#90 Make ESLint far more picky
  CONTRIBUTING.md
  nightwatch.conf.js
  package-lock.json
  package.json
  src/.eslintrc.json
  src/js/__tests__/parsers.js
  src/js/background.js
  src/js/components/ExtensionInfo.vue
  src/js/components/HypoAssignment.vue
  src/js/components/HypoGrades.vue
  src/js/helpers.js
  src/js/saspowerschoolff.js
  src/ui/historygrades.js
  src/ui/options.js
  tests/extensionInfo.js
Labels: enhancement

#99 Move final percent extract to a function
  src/css/spse.css
  src/js/__tests__/parsers.js
  src/js/helpers.js
  src/js/saspowerschoolff.js
Labels: enhancement, technical debt

#111 Add @gary-kim for Github Sponsors
  .github/FUNDING.yml
Labels: enhancement

#113 Fix options page can't find id error
  src/ui/options.js
Labels: bug

#115 Remove 0.25 weighting
  src/js/helpers.js
Labels: bug

#116 Update AUTHORS
  AUTHORS
Labels: enhancement

#118 Open Beta v0.18.2 Release
  CHANGELOG.md
  CONTRIBUTING.md
  package-lock.json
  package.json
Labels: maintenance
