Repository sas-fossdev/saspes, pull requests merged in 2020-03, with the labels that each got.

#126 Shows first semester GPA during second semester
  .gitignore
  src/js/saspowerschoolff.js
Labels: feature

#132 Preserve semver ranges for Renovate
  renovate.json
Labels: bug

#112 Add Missing Indicator on the Main Page and Classes for Course and Assignment
  .babelrc
  package-lock.json
  package.json
  src/css/spse.css
  src/js/components/ClassGrade.vue
  src/js/components/HypoGrades.vue
  src/js/helpers.js
  src/js/models/Assignment.js
  src/js/models/Course.js
  src/js/saspowerschoolff.js
  src/ui/options.html
Labels: feature

#129 Fix visual bug
  src/js/components/HypoAssignment.vue
Labels: bug

#138 Open Beta v0.20.0 Release
  CHANGELOG.md
  package-lock.json
  package.json
Labels: maintenance

#140 Added function to calculate cumulative GPA(including unfinished semesters)
  src/js/helpers.js
  src/js/models/Course.js
  src/js/saspowerschoolff.js
Labels: feature

#135 Tune Renovate config
  renovate.json
Labels: enhancement

#153 Added function to save grades to local storage and load grades from storage
  src/js/helpers.js
  src/js/models/Course.js
  src/js/saspowerschoolff.js
Labels: enhancement

#141 Fix an issue in HypoAssignment
  src/js/components/HypoAssignment.vue
Labels: bug, regression
