Repository sas-fossdev/saspes, pull requests merged in 2020-05, with the labels that each got.

#179 Open Beta v0.21.2 Release
  CHANGELOG.md
  package-lock.json
  package.json
Labels: maintenance

#181 Fixes cumulative GPA counting older version of semester
  src/js/components/CumulativeGPA.vue
Labels: bug

#183 Fix version name not being set
  webpack-helpers.js
  webpack.chromium.js
Labels: bug

#184 Open Beta v0.21.3 Release
  CHANGELOG.md
  package-lock.json
  package.json
Labels: maintenance

#186 Add Firefox update file script
  .travis.yml
  scripts/firefox-addon-update.js
  scripts/package-lock.json
  scripts/package.json
  src/manifest.json
Labels: feature
