Repository sas-fossdev/saspes, pull requests merged in 2020-04, with the labels that each got.

#160 Fixed bug where cumulative GPA calculation would double count semester
  src/js/saspowerschoolff.js
Labels: bug

#162 Fixes and cleanups for Course and cumulative GPA
  package-lock.json
  package.json
  src/js/components/CumulativeGPA.vue
  src/js/models/Course.js
  src/js/saspowerschoolff.js
Labels: bug

#168 Open Beta v0.21.0 Release
  CHANGELOG.md
  CONTRIBUTING.md
  package-lock.json
  package.json
Labels: maintenance

#169 Set Version Name Automatically
  CONTRIBUTING.md
  package.json
  webpack-helpers.js
Labels: enhancement

#175 Open Beta v0.21.1 Release
  CHANGELOG.md
  package-lock.json
  package.json
Labels: maintenance

#176 Remove clipboard read permission
  src/manifest - chromium.json
  src/manifest.json
Labels: bug
